UBUNTU: SAUCE: aufs -- Add missing argument to loop_switch() call
The aufs patches add an argument to loop_switch(), but an
additional call to this function was added since the patches were
last updated. This causes a FTBFS:

  drivers/block/loop.c: In function 'loop_flush':
  drivers/block/loop.c:624:9: error: too few arguments to function 'loop_switch'
    return loop_switch(lo, NULL);
           ^~~~~~~~~~~
  drivers/block/loop.c:596:12: note: declared here
   static int loop_switch(struct loop_device *lo, struct file *file,
              ^~~~~~~~~~~

This new call is meant only to induce a flush of queued bios and
does not use the file arguments at all, so just pass NULL.

Signed-off-by: Seth Forshee <seth.forshee@canonical.com>