UBUNTU: disable building bpf selftests (no VMLINUX_BTF)
BugLink: https://bugs.launchpad.net/bugs/1908144

Disable selftests/bpf since it cannot be built without having built vmlinux
first, else build fails with either:

    Makefile:148: *** cannot find a vmlinux for VMLINUX_BTF at any of
    "{paths}".  Stop.

or this more cryptic variant:

    Error: failed to load BTF from format: No such file or directory

Reference: "UBUNTU: SAUCE: selftests/bpf: clarify build error if no vmlinux"
Reference: https://lore.kernel.org/bpf/20201210185233.28091-1-broonie@kernel.org/
Signed-off-by: Kamal Mostafa <kamal@canonical.com>