Revert "UBUNTU: SAUCE: upstream v6.0: apparmor: Fix undefined reference to `zlib_deflate_workspacesize'"
BugLink: https://bugs.launchpad.net/bugs/1990236

This reverts commit 147c6a1f48c9c6b7656bbfecd02c83a49ea90933.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>