UBUNTU: SAUCE: upstream v6.0: apparmor: Fix undefined reference to `zlib_deflate_workspacesize'
BugLink: https://bugs.launchpad.net/bugs/1989983

IF CONFIG_SECURITY_APPARMOR_EXPORT_BINARY is disabled, there remains
some unneed references to zlib, and can result in undefined symbol
references if ZLIB_INFLATE or ZLIB_DEFLATE are not defined.

Reported-by: kernel test robot <lkp@intel.com>
Fixes: abfb9c0725f2 ("apparmor: make export of raw binary profile to userspace optional")
Signed-off-by: John Johansen <john.johansen@canonical.com>
(cherry picked from commit f9da5b14521cbb57ff45bd8134d3b8320638b1e6)
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>